// src/lib/constants/sudo.ts
export const SUDO_CONFIG = {
  SESSION_DURATION_MINUTES: 20,
  CODE_EXPIRATION_MINUTES: 10,
  RESEND_COOLDOWN_SECONDS: 30,
  MAX_RESEND_ATTEMPTS: 3,
  RESEND_WINDOW_MINUTES: 5,
  EXPIRING_SOON_THRESHOLD_MINUTES: 2,
} as const;
