// src/middleware.ts
//
// Edge-safe by design: this file must never import anything that touches
// the database (directly or transitively) — the libsql web/edge client
// cannot open `file:` URLs, and even hosted DB calls add latency/risk to
// every request. Session revocation (DB-backed) is enforced instead in
// Node-runtime code: getCurrentSession()/requireAuth() in auth-utils.ts,
// and the client-side checkAuth() in AuthContext, which calls /api/auth/me
// on mount and route change and will boot a user whose DB session has
// expired even though their JWT hasn't.
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { verifyJWT, JWT_COOKIE_NAME, type JWTPayload } from '@/lib/jwt';

// ============================================
// ROUTE TABLES
// ============================================

const AUTH_ROUTES = [
  '/login',
  '/register',
  '/2fa',
  '/forgot-password',
  '/reset-password',
  '/verify',
  '/verify-email',
];

// Only /login gets the "already logged in? bounce away" treatment.
// Middleware can't check DB session liveness (edge runtime, see header
// comment), so it shouldn't gate access to recovery flows (register,
// forgot-password, reset-password, 2fa, verify, verify-email) on "has a
// JWT" alone — a dead-session user could otherwise get trapped in a
// redirect loop instead of reaching the page that fixes their state.
const BOUNCE_IF_AUTHENTICATED_ROUTES = ['/login'];

// FIX: isPublicRoute() below now does prefix matching via matchesRoute(),
// the same way AUTH_ROUTES/ADMIN_ROUTES always have. Previously it only
// did exact-string matching, which is why '/resources' needed five
// separate child entries — any public sub-page not individually listed
// fell through to the old catch-all step and was allowed anyway (by
// accident, since the catch-all was open). Now a section root like
// '/resources' or '/ref' covers all of its children on its own. The
// specific child entries below are redundant now, not wrong — left in
// place so nothing regresses if this comment gets missed later.
const PUBLIC_ROUTES = [
  '/',
  '/forbidden',
  '/unauthorized',
  '/account-locked',
  '/about',
  '/blog',
  '/contact',
  '/privacy',
  '/terms',
  '/cookies',
  '/resources',
  '/resources/documentation',
  '/resources/guides',
  '/resources/faq',
  '/resources/api',
  '/resources/changelog',
  '/help',
  '/support',
  '/trial',
  '/splash',
  '/onboarding',
  // ASSUMPTION: referral links are clicked by signed-out visitors
  // sharing/following a link, so this has to stay public or the entire
  // referral funnel just redirects to /login. Confirm this is right —
  // if /ref/[code] expects a session, pull this entry.
  '/ref',
];

const PUBLIC_API_ROUTES = [
  '/api/auth/login',
  '/api/auth/logout',
  '/api/auth/forgot-password',
  '/api/auth/reset-password',
  '/api/auth/verify',
  '/api/auth/2fa',
  '/api/auth/resend-2fa',
  '/api/auth/notify-locked',
  '/api/auth/register',
  '/api/auth/verify-email',
  '/api/health',
  '/api/public',
  '/api/public/withdrawals/latest',
];

const ADMIN_ROLES = new Set(['SUPER_ADMIN', 'ADMIN']);

// ============================================
// ROUTE MATCHERS
// ============================================

function matchesRoute(pathname: string, routes: string[]): boolean {
  return routes.some(
    (route) => pathname === route || pathname.startsWith(route + '/'),
  );
}

const isPublicApiRoute = (p: string) => matchesRoute(p, PUBLIC_API_ROUTES);
const isAuthRoute = (p: string) => matchesRoute(p, AUTH_ROUTES);
const shouldBounceIfAuthenticated = (p: string) =>
  matchesRoute(p, BOUNCE_IF_AUTHENTICATED_ROUTES);

// FIX: any path under /admin is an admin route, full stop — no more
// enumerated list of every known /admin/* sub-page. A newly added admin
// page that forgot to register itself in the old ADMIN_ROUTES array
// would previously fall through to the open catch-all and be servable
// to a signed-out visitor with zero auth check. Prefix matching removes
// that failure mode entirely.
const isAdminRoute = (p: string) => p === '/admin' || p.startsWith('/admin/');

function isPublicRoute(pathname: string): boolean {
  if (pathname === '/') return true;
  if (matchesRoute(pathname, PUBLIC_ROUTES)) return true;
  if (pathname.startsWith('/_next')) return true;
  if (pathname.startsWith('/img')) return true;
  if (pathname.startsWith('/icons')) return true;
  if (pathname.startsWith('/fonts')) return true;
  if (pathname.startsWith('/favicon')) return true;
  if (pathname.startsWith('/manifest')) return true;
  // robots.txt / sitemap.xml are generated by robots.ts / sitemap.ts.
  // Crawlers hit these with no cookie at all — must stay public, or
  // default-deny below would 302 every crawler to /login.
  if (pathname.startsWith('/robots')) return true;
  if (pathname.startsWith('/sitemap')) return true;
  if (pathname.includes('#')) return true;
  return false;
}

// ============================================
// HELPERS
// ============================================

function redirectToLogin(request: NextRequest, pathname: string) {
  const loginUrl = new URL('/login', request.url);
  loginUrl.searchParams.set('from', pathname);
  const response = NextResponse.redirect(loginUrl);
  response.cookies.delete(JWT_COOKIE_NAME);
  return response;
}

function withAuthHeaders(request: NextRequest, payload: JWTPayload) {
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-user-id', payload.sub);
  requestHeaders.set('x-user-role', payload.role);
  requestHeaders.set('x-user-email', payload.email);
  requestHeaders.set(
    'x-user-roles',
    JSON.stringify(payload.roles || [payload.role]),
  );
  return NextResponse.next({ request: { headers: requestHeaders } });
}

// ============================================
// MIDDLEWARE
// ============================================

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  if (process.env.NODE_ENV === 'development') {
    console.log(`[MIDDLEWARE] ${pathname}`);
  }

  // 1. Public API routes
  if (isPublicApiRoute(pathname)) {
    return NextResponse.next();
  }

  // 2. Public frontend routes
  if (isPublicRoute(pathname)) {
    return NextResponse.next();
  }

  // 3. JWT check only — no DB access here (see file header comment)
  const token = request.cookies.get(JWT_COOKIE_NAME)?.value;
  let payload: JWTPayload | null = null;

  if (token) {
    try {
      payload = await verifyJWT(token);
    } catch (error) {
      console.error('[MIDDLEWARE] Token verification error:', error);
      return redirectToLogin(request, pathname);
    }
  }

  const role = payload?.role || 'USER';
  const isAdminUser = ADMIN_ROLES.has(role);

  // 4. Auth pages — only /login bounces an already-authenticated user
  // away (see BOUNCE_IF_AUTHENTICATED_ROUTES comment above).
  if (isAuthRoute(pathname)) {
    if (payload && shouldBounceIfAuthenticated(pathname)) {
      const destination = isAdminUser ? '/admin/dashboard' : '/dashboard';
      return NextResponse.redirect(new URL(destination, request.url));
    }
    return NextResponse.next();
  }

  // 5. Admin routes — require auth + admin role
  if (isAdminRoute(pathname)) {
    if (!payload) return redirectToLogin(request, pathname);
    if (!isAdminUser) {
      return NextResponse.redirect(new URL('/unauthorized', request.url));
    }
    return withAuthHeaders(request, payload);
  }

  // 6. Everything else is protected by default.
  //
  // FIX: this used to be an enumerated DASHBOARD_ROUTES allowlist
  // ('/dashboard', '/wallet', '/earn', ...) with a final catch-all that
  // let anything NOT on that list through with no auth check at all.
  // That's exactly how '/notifications' ended up servable without a
  // session — it's a real page under the (dashboard) route group, it
  // just was never added to the array. Default-deny means a new page
  // added anywhere that isn't explicitly public/auth/admin is protected
  // automatically and can't be missed the same way again.
  if (!payload) {
    if (pathname.startsWith('/api/')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    return redirectToLogin(request, pathname);
  }

  // FIX: this is the actual "admin ends up on the consumer dashboard"
  // bug. An authenticated ADMIN/SUPER_ADMIN hitting a consumer route
  // (/dashboard, /wallet, /earn, /notifications, anything under here
  // that isn't /admin/*) used to just get in, because this branch only
  // ever checked "is there a payload," never "does this role belong
  // here." Admins now get bounced to the admin panel instead.
  //
  // Left off the /api branch on purpose — the admin panel's own pages
  // may legitimately call shared consumer API routes (e.g. /api/wallet)
  // for data-fetching. It's page access that should be exclusive, not
  // API access.
  if (isAdminUser && !pathname.startsWith('/api/')) {
    return NextResponse.redirect(new URL('/admin/dashboard', request.url));
  }

  if (pathname.startsWith('/api/')) {
    return NextResponse.next();
  }

  return withAuthHeaders(request, payload);
}

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|img/|fonts/|assets/).*)',
  ],
};
